### ISSUE TITLE
Warning with FROM as - and Docker file does not actulay run debuild

### ISSUE THREAD

**Issue by jobby889** [jnicolson/gasket-builder#1]
I suspect you omitted the build when you removed the patch.... and FROM as is just a warning, but great work thxs....

I believe Docker file should be (As in pre-patch version + 24.04 )

FROM ubuntu:24.04 AS build-stage

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -q -y --no-install-recommends git devscripts dkms dh-dkms build-essential debhelper

RUN git clone https://github.com/google/gasket-driver.git
RUN cd gasket-driver && debuild -us -uc -tc -b

FROM scratch AS export-stage
COPY --from=build-stage /build/*.deb .

**Comment by jnicolson** [comment]
Thanks!  Thats interesting, I'd never seen that error before - wonder if it's a recent change to docker.  Easy fix though, thanks for the report!
